### ISSUE TITLE
How to expand a Memory object?

### ISSUE THREAD

**Issue by Superice666** [kawamuray/wasmtime-java#6]
@kawamuray A standard webassembly memory only has a linear space of 64KB. It seems that we can make it bigger by calling `memory.grow()`, howerver, I find no jni bindings for this. Is there any other ways to do this? Thank you!

**Comment by kawamuray** [comment]
You always submit a PR before I answer your question,  so quick ;D
As you did already, yes, that needs to be implemented to use that method.
I'll review #7 then :)

**Comment by Superice666** [comment]
Finish,close.
